import React from 'react';
import { Layers, Bot, Database, Sparkles, MessageSquare, Edit3, Shield } from 'lucide-react';
import { PublicLayout, PublicPageType } from '../components/PublicLayout';

interface PageProps {
   onNavigate: (page: PublicPageType) => void;
   onEnterApp: () => void;
}

export const TaskTypes: React.FC<PageProps> = ({ onNavigate, onEnterApp }) => {
   return (
      <PublicLayout currentPage="task-types" onNavigate={onNavigate} onEnterApp={onEnterApp}>
         <section className="py-24 px-6 relative overflow-hidden min-h-[80vh]">
            <div className="max-w-7xl mx-auto">
               <div className="mb-16 text-center">
                  <span className="text-blue-600 dark:text-blue-400 font-bold uppercase tracking-widest text-xs mb-2 block">Our Task Library</span>
                  <h1 className="text-4xl md:text-6xl font-black mb-6 tracking-tighter leading-tight">
                     <span className="text-slate-900 dark:text-white">Diverse Tasks for </span>
                     <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-700 via-blue-500 to-blue-700 dark:from-blue-600 dark:via-blue-500 dark:to-blue-600 animate-shimmer drop-shadow-md">Every Skill Level</span>
                  </h1>
                  <p className="text-slate-600 dark:text-zinc-400 max-w-3xl mx-auto text-xl leading-relaxed">
                     Whether you are a coding expert or a native language speaker, Starset has a task for you. 
                     Train the next generation of AI by classifying, writing, and evaluating model outputs.
                  </p>
               </div>

               <div className="grid lg:grid-cols-3 gap-8 mt-16">
                  {/* Task Card 1 */}
                  <div className="bg-slate-50 dark:bg-zinc-900/50 backdrop-blur-md p-10 rounded-[2rem] border border-slate-200 dark:border-white/10 relative group hover:-translate-y-2 transition-all duration-300">
                     <div className="h-14 w-14 bg-indigo-100 dark:bg-indigo-900/20 rounded-2xl flex items-center justify-center text-indigo-600 dark:text-indigo-400 mb-8 border border-indigo-200 dark:border-indigo-900/30 group-hover:scale-110 transition-transform">
                        <MessageSquare className="h-7 w-7" />
                     </div>
                     <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">RLHF Text Evaluation</h3>
                     <p className="text-slate-600 dark:text-zinc-400 leading-relaxed">
                        Read two different responses generated by an AI model and select which one is safer, more helpful, and more accurate based on complex guidelines.
                     </p>
                  </div>

                  {/* Task Card 2 */}
                  <div className="bg-slate-50 dark:bg-zinc-900/50 backdrop-blur-md p-10 rounded-[2rem] border border-slate-200 dark:border-white/10 relative group hover:-translate-y-2 transition-all duration-300">
                     <div className="h-14 w-14 bg-emerald-100 dark:bg-emerald-900/20 rounded-2xl flex items-center justify-center text-emerald-600 dark:text-emerald-400 mb-8 border border-emerald-200 dark:border-emerald-900/30 group-hover:scale-110 transition-transform">
                        <Database className="h-7 w-7" />
                     </div>
                     <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Data Labeling & Tagging</h3>
                     <p className="text-slate-600 dark:text-zinc-400 leading-relaxed">
                        Identify and categorize elements in massive datasets. Apply metadata to images, texts, and audio clips to give machine learning models the context they need.
                     </p>
                  </div>

                  {/* Task Card 3 */}
                  <div className="bg-slate-50 dark:bg-zinc-900/50 backdrop-blur-md p-10 rounded-[2rem] border border-slate-200 dark:border-white/10 relative group hover:-translate-y-2 transition-all duration-300">
                     <div className="h-14 w-14 bg-blue-100 dark:bg-blue-900/20 rounded-2xl flex items-center justify-center text-blue-600 dark:text-blue-400 mb-8 border border-blue-200 dark:border-blue-900/30 group-hover:scale-110 transition-transform">
                        <Edit3 className="h-7 w-7" />
                     </div>
                     <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Creative Writing</h3>
                     <p className="text-slate-600 dark:text-zinc-400 leading-relaxed">
                        Write high-quality prompts and craft the perfect human responses. Teach the AI how to summarize, translate, and creatively write essays from scratch.
                     </p>
                  </div>
               </div>
            </div>
         </section>
      </PublicLayout>
   );
};
